### PR TITLE
Update rust plugin

### PR DESCRIPTION
**Pull request by imbsky**

### CODE REVIEW

**Comment by imbsky** [comment]
Build status](https://github.com/asdf-community/asdf-rust/actions)

**Comment by Stratus3D** [comment]
What is wrong with rustup? I generally prefer plugins that wrap well-maintained community build scripts. In the last couple years we switched asdf-ruby to use ruby-build underneath, and asdf-erlang to use kerl. Both of these tools allow to stay more up to date with new versions as there are already teams that maintain them and update them within days of new versions being released.

**Comment by imbsky** [comment]
I see. I thought that the script just wrapped was not suitable for asdf. but that sounds reasonable enough. Anyway, I'll revert this change.

**Comment by Stratus3D** [comment]
It's really whatever is easiest to maintain. If restup is too cumbersome to use in a plugin then writing a plugin from scratch is fine.

**Comment by imbsky** [comment]
That makes sense!

**Pull request merged**
