### PR TITLE
add plugin container-diff

### PR DESCRIPTION
**Pull request by cgroschupp**

### CODE REVIEW

**Comment by imbsky** [comment]
Add it to the README as well.

**Comment by cgroschupp** [comment]
@imbsky done

**Comment by cgroschupp** [comment]
@imbsky ready to merge?

**Comment by imbsky** [comment]
I'm really sorry, I'm busy with the exam this month, so I don't have much time to see it. But I'm not forgetting about this, so I'll definitely check it again as soon as possible.

**Comment by imbsky** [comment]
Please remove this unused variable. But overall it looks good 🙂
https://github.com/cgroschupp/asdf-container-diff/blob/298893ef9ec31134c628f046d7355cd6aeedb640/bin/install#L33

**Comment by vic** [comment]
I'm merging this. LGTM.

 @cgroschupp, perhaps you might want to remove the unused variable pointed by @imbsky.

**Pull request merged**
