### PR TITLE
[New Plugin] pack (buildpack.io)

### PR DESCRIPTION
**Pull request by johnlayton**

### CODE REVIEW

**Comment by johnlayton** [comment]
Renamed to buildpack to reflect the tool name correctly.

**Comment by vic** [comment]
Hello, can you please rebase ?

**Comment by johnlayton** [comment]
Rebased

**Comment by jthegedus** [comment]
@vic Are we ignoring Travis atm?

**Comment by vic** [comment]
The Travis build in this repo can be safely ignored by now since it depends on all plugins being green.

For new plugin PR, just make sure new plugin additions have a CI build setup  (preferably using asdf gihub actions) and that it's green at the time of merging.

**Comment by jthegedus** [comment]
@vic I don't seem to have permissions to merge despite being added to the asdf-plugin team :thinking:

**Comment by vic** [comment]
@jthegedus fixed now, for some reason the @asdf-vm/plugins team had no access to this repo  :/

**Pull request merged**
