### PR TITLE
Link pachctl plugin

### PR DESCRIPTION
**Pull request by abatilo**
This plugin installs pachctl which is the CLI tool for pachyderm.

# Checklist

- [X] Provide a short description and link to your plugin.

- [X] Make sure you CI tests for your plugin and they are green.

      If you are using github, you might want to use the
      `plugin_test` action from [asdf-actions](https://github.com/asdf-vm/actions)

- [X] `asdf-plugins` CI sanity checks are green on your PullRequest.

      You can test locally using:

      ```bash
      ./test_plugin.sh --file plugins/PLUGIN_FILE
      ```

Thank you for contributing to asdf-plugins!

### CODE REVIEW

**Comment by abatilo** [comment]
@smorimoto I would greatly appreciate if you could take a look!

Thank you in advanced.

**Review by smorimoto — APPROVED** [review]

**Comment by smorimoto** [comment]
It's recommended that you use v1 instead. The others look good.
https://github.com/abatilo/asdf-pachctl/blob/f7730ff4ac08f0d4f227dfe5d890c7e8ebfdf235/.github/workflows/test.yml#L17

**Comment by smorimoto** [comment]
Thanks @abatilo!

**Comment by abatilo** [comment]
Thank you very very much for that quick response!

**Pull request merged**
