### PR TITLE
feat: provide promtool

### PR DESCRIPTION
**Pull request by looztra**
| Language  | Repository  | CI Status
|-----------|-------------|----------
| promtool | [looztra/asdf-promtool](https://github.com/looztra/asdf-promtool) | [Build Status](https://travis-ci.org/looztra/asdf-promtool)

### CODE REVIEW

**Comment by Stratus3D** [comment]
Is promtool the only prometheus component that can be managed by asdf? If not, I'd suggest adding support for all of prometheus, although I'm not very experienced with prometheus so I'm not sure what that would involve, or if it would even be useful, but it doesn't seem good to limit this to a single command.

asdf-prometheus would also be a more recognizable name. I'd not heard of promtool until now.

**Comment by looztra** [comment]
prometheus is more a server component.

promtool is used to check configuration files and unit test alert
definitions.

So in my opinion, that's the only one that is legitimate to be use as a
standalone tool

**Comment by Stratus3D** [comment]
I'm thinking about people who might want to run different versions of the prometheus server locally. We have plugins for numerous database servers, so it seems some users might want to run a prometheus server locally. Would it be difficult to expand this plugin to also support the `prometheus` server executable as well?

**Comment by looztra** [comment]
Roger that. I will adjust the plugin an rename it like suggested.

Le mer. 14 août 2019 à 22:18, Trevor Brown <notifications@github.com> a
écrit :

**Comment by imbsky** [comment]
What is the status of this PR?

**Comment by Stratus3D** [comment]
@imbsky I don't see any updates to the plugin code since our last comments. Closing since we haven't heard anything.

**Pull request closed without merging**
