### PR TITLE
fix: update jq plugin repo url

### PR DESCRIPTION
**Pull request by jaymecd**
Replace plugin repo as current plugin maintainer is not responding.

Fixes:
- Update URLs to point to jqlang/jq instead of stedolan/jq
- Add arm64 architecture support

## Summary

Description:

- Tool repo URL: https://github.com/jqlang/jq.git
- Plugin repo URL: https://github.com/lsanwick/asdf-jq.git

## Checklist

- [x] Format with `scripts/format.bash`
- [x] Test locally with `scripts/test_plugin.bash --file plugins/<your_new_plugin_name>`
- [x] Your plugin CI tests are green
  - _Tip: use the `plugin_test` action from [asdf-actions](https://github.com/asdf-vm/actions) in your plugin CI_

### CODE REVIEW

**Review by jthegedus — CHANGES_REQUESTED** [review]
You will need to update the links in the README for the plugin too

**Comment by jaymecd** [comment]
nice catch @jthegedus, it's updated now

**Comment by jaymecd** [comment]
This is a great question and I pass it directly @lsanwick to respond.

@oeuftete is there a program to onboard plugin (not just binding) under official `asdf` organization?

**Comment by lsanwick** [comment]
Hi @jaymecd and @oeuftete! I'm happy to maintain the fork going forward, especially given it isn't a very large amount of code.  Is there anything I need to do to make it ready to be the "official" plugin?

**Comment by jthegedus** [comment]
Plugins in this repo are not considered official. This repo exists to save typing out the URLs for the plugin repos you wish to use.

As stated in the README here and docs site:

>The asdf core team recommend using the long-form which does not rely on this repository:
>`asdf plugin add <name> <git_url>`

Additionally, changing plugins listed here on effects new installations of plugins, if you have a previously removed plugin, performing `asdf plugin update <name>` it will not change the repository of the already installed plugin. To do that you must remove the plugin then add the latest. Again, using the long-form plugin add makes this clearer to users and we recommend it.

**Review by jthegedus — APPROVED** [review]
Thanks

**Pull request merged**
