### PR TITLE
Add esy

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Comment by imbsky** [comment]
Build Status: [Build Status](https://github.com/asdf-community/asdf-esy/actions)

**Comment by Stratus3D** [comment]
Is an asdf plugin needed for esy? It looks like it can easily be installed with npm.

**Comment by imbsky** [comment]
In my opinion, non-npm users may also use esy. In that case, it's little troublesome to install a package manager for install a package manager. This is the same reason why I use asdf for yarn (alternative to npm). As far as I remember, if you install yarn with brew, Node.js is always installed as a dependency (except that install yarn with `--ignore-dependencies` option). and The Node.js installed with brew is never to be used if you install node with asdf. To avoid such problems, we decided to create this plugin.

**Comment by Stratus3D** [comment]
That makes sense. Thank you for the PR!

**Pull request merged**
