### PR TITLE
Add Minishift plugin

### PR DESCRIPTION
**Pull request by sqtran**
# Checklist

- [X] Provide a short description and link to your plugin.

   Minishift is a tool for deploying a local Openshift 3.x cluster.   See details here -> https://github.com/sqtran/asdf-minishift

- [X] Make sure you CI tests for your plugin and they are green.

  CI

- [X] `asdf-plugins` CI sanity checks are green on your PullRequest.
 
```bash
$ ./test_plugin.sh --file plugins/minishift 
Checking plugins/minishift
OK plugins/minishift
```
## Other Information
Please enjoy this delicious plugin.

### CODE REVIEW

**Comment by sqtran** [comment]
Not sure what that failing check means, could someone give me some suggestions as to how to debug?

**Comment by sqtran** [comment]
Hey @vic , looks like the last 4 plugins that were successfully merged into master also failed this test.  Guessing that there's nothing else I need to do but wait for a manual override.  LMK if you need anything from me.

**Comment by smorimoto** [comment]
That was fixed now. Also, the plugin code looks good.

**Comment by smorimoto** [comment]
Thanks @sqtran!

**Pull request merged**
