### PR TITLE
feat: chamber plugin

### PR DESCRIPTION
**Pull request by johnnyplaydrums**
Hi there! This PR adds [the plugin](https://github.com/mintel/asdf-chamber) for a secrets management tool called [chamber](https://github.com/segmentio/chamber).

Thank you for the awesomeness that is `asdf` and `asdf-plugins`!

# Checklist

- [x] Provide a short description and link to your plugin.
- [x] Make sure you CI tests for your plugin and they are green.
- [x] `asdf-plugins` CI sanity checks are green on your PullRequest.

### CODE REVIEW

**Review by jthegedus — APPROVED** [review]
LGTM, thanks

**Comment by johnnyplaydrums** [comment]
Thank you @jthegedus!

**Comment by johnnyplaydrums** [comment]
Hey @jthegedus, what's the process for updating my local setup to use the most recent version of this repo? My local installation can't find the plugin yet as `asdf plugin-add chamber` says not found and `asdf plugin-list-all | grep chamber` is empty.

**Comment by jthegedus** [comment]
@johnnyplaydrums From my memory, your local cache of the `asdf-plugins` repo updates once per day. I will be looking to make enhancements here in the future

**Comment by johnnyplaydrums** [comment]
@jthegedus yep I think it took a day or two but now were are good to go. Thanks again!

**Pull request merged**
