### PR TITLE
Add Hamler plugin

### PR DESCRIPTION
**Pull request by scudelletti**
Hello, this PR adds the plugin for Hamler Lang and it aims to help asdf users to install Hamler.

> Hamler is a strongly-typed language with compile-time typechecking and built-in support for concurrency and distribution. 

More info please check [Hamler's website](https://www.hamler-lang.org/).

Build Status: Build

# Checklist

- [x] Provide a short description and link to your plugin.

- [x] Make sure you CI tests for your plugin and they are green.

      If you are using github, you might want to use the
      `plugin_test` action from [asdf-actions](https://github.com/asdf-vm/actions)

- [x] `asdf-plugins` CI sanity checks are green on your PullRequest.

      You can test locally using:

      ```bash
      ./test_plugin.sh --file plugins/PLUGIN_FILE
      ```

## Other Information

I also moved `httpie-go` down since it wasn't in the correct position/order. 

Thank you for maintaining ASDF, it is a great project! Well done! 💐

### CODE REVIEW

**Comment by scudelletti** [comment]
Hi @smorimoto, could you please take a look when you have time?

I'm tagging you because you are the person with more activity in this repo.

**Review by smorimoto — APPROVED** [review]

**Comment by smorimoto** [comment]
The code in the plugin repository itself looks pretty verbose to me, but that's not a big problem.

**Comment by smorimoto** [comment]
Sorry for the late review. I was a little busy.

**Comment by smorimoto** [comment]
Thanks @scudelletti!

**Pull request merged**
