### PR TITLE
Add plugin for anchore/grype

### PR DESCRIPTION
**Pull request by poikilotherm**
# Checklist

Install the [Anchore Security Scanner "grype"](https://github.com/anchore/grype) with [this plugin](https://github.com/poikilotherm/asdf-grype).

- [X] Provide a short description and link to your plugin.
- [X] Make sure you CI tests for your plugin and they are green.
- [x] `asdf-plugins` CI sanity checks are green on your PullRequest.

### CODE REVIEW

**Comment by poikilotherm** [comment]
You're kidding me folks.

Prettier complains about nonsense syntactic sugar:
image

And on re-running the CI job, it doesn't seem to fetch the latest main branch. :partying_face:

**Comment by smorimoto** [comment]
Wouldn't it be better to remove paste and make it behave like any other plugins?
https://github.com/poikilotherm/asdf-grype/blob/4808ea865e4c7d1c90651f8b342a9da8eaec782c/bin/list-all#L17

**Comment by poikilotherm** [comment]
I strongly disagree.

- [Shellcheck](https://www.shellcheck.net) is picky about not double quoting in https://github.com/poikilotherm/asdf-grype/blob/4808ea865e4c7d1c90651f8b342a9da8eaec782c/bin/list-all#L18.
- Looking at https://github.com/asdf-vm/asdf/blob/51a283a41d2d568a9f02ec36a43850723d4565a7/lib/commands/command-list-all.bash#L19, asdf relies on the space char.
- `$versions` is multiline output, separated by `\n`, not ` `. So we are relying on implicit conversion here.
- The quoting on the `echo` makes it a string, resulting in a broken `asdf list-all grype`, only printing the first release (again, as the `while read` relies on `IFS=' '`

I switched to using `paste` in poikilotherm/asdf-grype@a54c4c97 due to this.

**Comment by smorimoto** [comment]
​I was thinking of using xargs instead, but paste seems faster because it doesn't create new processes. ​That looks good!

**Review by smorimoto — APPROVED** [review]

**Comment by smorimoto** [comment]
Thanks @poikilotherm!

**Pull request merged**
