### PR TITLE
refactor: rename osctl to talos

### PR DESCRIPTION
**Pull request by particledecay**

### CODE REVIEW

**Comment by Stratus3D** [comment]
The build is failing because of the talos plugin and I'm not sure why.

**Comment by imbsky** [comment]
Perhaps this PR can be merged. Can you rebase this? @particledecay

**Comment by particledecay** [comment]
Will do tonight

**Comment by imbsky** [comment]
Thanks!

**Comment by imbsky** [comment]
Looks good to me.

**Comment by imbsky** [comment]
Thanks @particledecay for your contribution! and I'm sorry for the late response to this PR.

**Pull request merged**
