### PR TITLE
Change repository for asdf-jq

### PR DESCRIPTION
**Pull request by AZMCode**
# Checklist

- [x] A plugin to manage [jq](https://github.com/AZMCode/asdf-jq)

- [x] Make sure you CI tests for your plugin and they are green.

- [x] `asdf-plugins` CI sanity checks are green on your PullRequest.

## Other Information

The original repo did not ever work for linux downloads, worked only for some osx downloads.
The old plugin also currently has  failing CI.
This, and the addition of a download script (It's basically a shim for install) makes me think my fork could be a better default for asdf users.
These fixes have been posted as a PR on the [original repo](https://github.com/focused-labs/asdf-jq), but months of inactivity, despite the pending issues, make me think the original repo might be dead.

### CODE REVIEW

**Comment by AZMCode** [comment]
As of currently, master is not ready to use. Converting to draft.

**Comment by AZMCode** [comment]
Alright, I think this is ready for review now

**Comment by AZMCode** [comment]
Just added source download and installs as well

**Comment by smorimoto** [comment]
FYI: @austinbv

**Comment by smorimoto** [comment]
@austinbv If you don't have the bandwidth to maintain it anymore, I recommend moving the plugin to the asdf-community.

**Comment by austinbv** [comment]
We will update this week - sorry we didn't realize that it was broken

**Comment by AZMCode** [comment]
Don't worry. Thanks for the help!

**Comment by smorimoto** [comment]
@austinbv I’m always ready to help with the migration and/or maintenance. Please feel free to ping me.

**Comment by AZMCode** [comment]
I'll make a PR on the repo to include these changes

**Comment by AZMCode** [comment]
Any progress with merging?

**Pull request closed without merging**
