### PR TITLE
Add neovim plugin

### PR DESCRIPTION
**Pull request by richin13**
[Build Status](https://travis-ci.org/richin13/asdf-neovim)

### CODE REVIEW

**Comment by imbsky** [comment]
I think you can make the list-all script simpler by writing like this.

```bash
curl -sL https://api.github.com/repos/neovim/neovim/tags | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+" | sort_versions
```

**Comment by Stratus3D** [comment]
Thanks for the PR @richin13. I'm going to go ahead and merge, but I agree with what @imbsky said about the version code in the `list-all` script. A simpler solution exists.

**Comment by richin13** [comment]
I completely missed @imbsky's comment. 

I'll make the update. Thanks guys :+1:

**Comment by imbsky** [comment]
👍

**Comment by richin13** [comment]
@imbsky I ended up using a variation of one of your suggestions using [this regex](https://regex101.com/r/jfRwKp/1) for the replacement.

**Comment by imbsky** [comment]
Great!

**Pull request merged**
