### PR TITLE
add new repo for the kubectx tool

### PR DESCRIPTION
**Pull request by johnlayton**
Sorry not renamed, however I have migrated to the asdf GitHub Actions for testing.
I have also scheduled the builds.  Badges should now be green.

Any chance that I can move all these to the asdf-community?

### CODE REVIEW

**Comment by imbsky** [comment]
The code looks good to me. Yes, transfer is fine, but you will need to change the repository name. Such naming significantly reduces searchability.

**Comment by johnlayton** [comment]
@imbsky yeap no problem the names should be meaningful to users.

**Comment by imbsky** [comment]
Ok, could you transfer the repository first?

**Comment by johnlayton** [comment]
I have updated the repo names under my user.

**Comment by johnlayton** [comment]
I have removed the kubectx plugin, to the PR wording is incorrect.

**Pull request closed without merging**
