### PR TITLE
Add kubecfg

### PR DESCRIPTION
**Pull request by nikolay**
https://github.com/ksonnet/kubecfg

### CODE REVIEW

**Comment by nikolay** [comment]
Thanks, @vic!

**Comment by vic** [comment]
@nikolay Thanks to you.

Just a headsup, the travis ci is failing for your plugin.

**Comment by nikolay** [comment]
@vic I'm trying to fix that by not using the notorious rate-limited GitHub API, but just Git for fetching the tags/releases. The plugin itself is otherwise working just fine.

**Comment by nikolay** [comment]
@vic Fixed! What I did is pretty universal and should go in the [asdf](https://github.com/asdf-vm/asdf) standard library:
* get all SemVer-like tags from a repository without cloning it;
* sort those SemVer versions in ascending order.

I wish I was better at `awk`! I tried not using a loop and doing all parsing and extraction in one pass, but couldn't do it.

**Pull request merged**
