### PR TITLE
🔥 Remove unstable plugins

### PR DESCRIPTION
**Pull request by canterberry**
> :warning: **Note:** This PR removes plugins for some well-known tools. It is a heavyweight one-time approach to solving #84. Prior to merging, the maintainers of these plugins should be notified and given the opportunity to fix their builds.

Each removed plugin currently has a failing Travis CI build.

The intended result of this commit is to achieve a passing Travis CI build for this repo.

## Plugins Affected

 * https://github.com/iroddis/asdf-R
 * https://github.com/Ibotta/asdf-brig.git
 * https://github.com/marciogm/asdf-crystal.git
 * https://github.com/paxosglobal/asdf-dep
 * https://github.com/endorama/asdf-desk.git
 * https://github.com/mikestephens/asdf-elasticsearch
 * https://github.com/asdf-vm/asdf-elixir
 * https://github.com/vic/asdf-elm.git
 * https://github.com/oae/asdf-flutter.git
 * https://github.com/stefansedich/asdf-fluxctl
 * https://github.com/vic/asdf-graalvm
 * https://github.com/rfrancis/asdf-gradle
 * https://github.com/vic/asdf-haskell.git
 * https://github.com/halcyon/asdf-java.git
 * https://github.com/rkyleg/asdf-julia.git
 * https://github.com/stefansedich/asdf-kubeseal.git
 * https://github.com/alvarobp/asdf-minikube
 * https://github.com/sylph01/asdf-mongodb.git
 * https://github.com/vic/asdf-ocaml.git
 * https://github.com/smashedtoatoms/asdf-openresty.git
 * https://github.com/odarriba/asdf-php
 * https://github.com/paxosglobal/asdf-protoc
 * https://github.com/smashedtoatoms/asdf-redis
 * https://github.com/code-lever/asdf-rust
 * https://github.com/mtatheonly/asdf-scala
 * https://github.com/RykHawthorn/asdf-tflint

### CODE REVIEW

**Comment by canterberry** [comment]
:bulb: **Note:** This PR, really, is just complementary to #84 to help kick off a conversation. I don't actually think it should be merged (unless these plugins are, indeed, defunct).

**Comment by stefansedich** [comment]
@canterberry I will take a look at my two in that list (fluxctl and kubeseal), however looking at the travis build I have setup for them they are green, is there any way to get more debug info for them? looking at the builds as part of my original PR there is nothing useful.

**Comment by canterberry** [comment]
@stefansedich I'm looking at the README, and your two look [fine now](https://github.com/asdf-vm/asdf-plugins#plugin-list). I pulled my list from [this failed Travis CI build](https://travis-ci.org/asdf-vm/asdf-plugins/builds/536791610) from May 24, 2019. Looks like they were still failing in [#161](https://travis-ci.org/asdf-vm/asdf-plugins/builds/538240221).

It's possible that the **test.sh** methodology (used by the Travis CI build in this repo to determine pass/fail based on README badges) is flawed in some way unrelated to the stability of an individual project. For example, maybe hitting API limits or throttling of some kind.

**Comment by elementalvoid** [comment]
I haven't had a chance to look at a fix, but I notice that `test.sh` is not checking the "target branch" -- by that I mean the branch that the status links point to in Travis.

For example: the Ibotta/brig plugin...
The status image points at the `master` branch. And this branch is in fact passing. However, `test.sh` **only checks the latest build** which is indeed failing. But it's a PR that is failing, not the "released" master branch.

I suspect the others are similar.

**Comment by elementalvoid** [comment]
@canterberry I took some time to update the `test.sh` script; see #88. It doesn't fix the root issue you're concerned about (knowing the state of plugins) but it should help.

**Comment by canterberry** [comment]
Closing this advisory PR for archival.

**Comment by Stratus3D** [comment]
Thanks for creating this PR @canterberry. Sorry to be so behind on this repo. I think we should remove plugins with failing builds, but I'm not sure what the rules should be. A minor, temporary, mistake shouldn't be enough to get a plugin removed. But a persistently failing and unmaintained plugin should be removed.

**Pull request closed without merging**
