### PR TITLE
Add ghq

### PR DESCRIPTION
**Pull request by kajisha**

### CODE REVIEW

**Comment by imbsky** [comment]
The code looks good. There was a syntax error in the markdown, so please check it next time before opening PR.

**Comment by imbsky** [comment]
Thanks @kajisha for your contribution!

**Comment by kajisha** [comment]
> The code looks good. There was a syntax error in the markdown, so please check it next time before opening PR.

Thank you for fixing. I will take care before commit.

**Comment by imbsky** [comment]
No worries! Also, don't forget to copy and paste a CI badge into the PR's description 🙂

**Pull request merged**
