### PR TITLE
adding kubectl

### PR DESCRIPTION
**Pull request by rubbish**
From http://kubernetes.io

### CODE REVIEW

**Comment by vic** [comment]
Hello,

Looks like the travis build for your plugin is failing, could you just check that before we could merge these changes?. Thank you.

**Comment by rubbish** [comment]
@vic It's passing now, just waiting on the Mac OS build to finish. There was some github api rate limiting affecting things. Adding a travisci env var for a github token made it pass. Thanks.

**Comment by rubbish** [comment]
All green now.

**Comment by vic** [comment]
Nice, tank you <3

**Pull request merged**
