### PR TITLE
feat: Welcome awscli-local to the family

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
## Summary

Description:

- Tool repo URL: https://github.com/localstack/awscli-local#usage
- Plugin repo URL: https://github.com/paulo-ferraz-oliveira/asdf-awscli-local

## Checklist

- [x] Format with `scripts/format.bash`
- [x] Test locally with `scripts/test_plugin.bash --file plugins/<your_new_plugin_name>`
- [x] Your plugin CI tests are green
  - _Tip: use the `plugin_test` action from [asdf-actions](https://github.com/asdf-vm/actions) in your plugin CI_

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
Opened as draft to make sure CI is ✅.

**Comment by paulo-ferraz-oliveira** [comment]
CI failing. I couldn't find any mention to the fact that you're using conventional commits. I will make sure I follow that, but maybe the contributing instructions could mention it (?)

**Comment by paulo-ferraz-oliveira** [comment]
Force pushed to have the commit as "conventional".

**Comment by paulo-ferraz-oliveira** [comment]
"2 workflows awaiting approval"... other than that, I think it's ready for review.

**Review by jthegedus — APPROVED** [review]
Thanks!

**Pull request merged**
