### PR TITLE
add multiple tools using asdf-github-release-downloader

### PR DESCRIPTION
**Pull request by laidbackware**
Generic plugin which supports multiple Github binaries - https://github.com/laidbackware/asdf-github-release-downloader

## Other Information

This is for a script which supports multiple tools from github.
Manually created tests run against the latest asdf tag and version 0.6.3 for backwards compatibility.

Currently supports:
- antctl
- bosh
- credhub
- fly
- govc
- imgpkg
- kubelogin
- om
- pivnet
- sonobuoy
- s5cmd

### CODE REVIEW

**Comment by laidbackware** [comment]
CI is currently failing because it expects a single pull request for 1 plugin, this pull request is for a plugin for 12 tolls. Can an exception be made, given that this plugin is designed to support multuple tools?

**Comment by jthegedus** [comment]
@laidbackware I appreciate the want to maintain fewer plugins, but when the only thing these tools have in common is they're sourced from GitHub it makes it a bit odd to install a plugin called `github-tools` and none of the tools it installs are GitHub tools (like the `gh` CLI).

The purpose of our plugin-templte is to make building plugins sourcing GitHub easier, would you consider renaming this plugin or splitting some of the similar tools (vmware) out into their own plugins?

This raises the discussion of should we handle some sources by default in the core? :thinking:

**Comment by laidbackware** [comment]
@jthegedus I've renamed to make clear it's a generic github release download tool. Is this OK or do you want me to strip out the 2 non-VMware related tools?

I agree that there should be a generic default tool in core which handles single binary downloads within core, as there is only minimal change between different github projects. Although it does introduce some interesting questions, as who is responsible for tracking and debugging behaviour chanages, such as if a product owner decides to change the names of their binaries within a release. 

I think it may make more sense to have a github release plugin template for 95% of use cases which people fork, that template can download tools via an external config file. The owner of the forked plugin is then responsible for testing, which should be set to trigger on a weekly schedule - or somehow per release, but that would mean 1:1 plugin repo to release. Then should an update to the base template be needed, such as splitting install/download, you could have core CI auto add issues to the forked repos to merge updates.

**Comment by jthegedus** [comment]
>@jthegedus I've renamed to make clear it's a generic github release download tool. Is this OK or do you want me to strip out the 2 non-VMware related tools?

This plugin is too generic for me to merge. It should be at most, one plugin for `vmware` tools, another for `pivotal`, another for `cloudfoundry` etc. That way it is somewhat clear what these plugins do and they can manage the tools somewhat separately.

>I think it may make more sense to have a github release plugin template for 95% of use cases which people fork, that template can download tools via an external config file

Our plugin template tries to make this easier for authors to get started - https://github.com/asdf-vm/asdf-plugin-template

It is built to support GitHub releases out of the box. Fork and run the setup script and it should do most the work for you.

I should not have suggested a default download in the core, we may add an API at some point, but the purpose for a plugin per binary, is so that we can support workflows for specific binaries that need them. If you look at the `asdf-nodejs` plugin - https://github.com/asdf-vm/asdf-nodejs/tree/master/bin - you can see that it has scripts for managing not only `install`, but also `postinstall`, `exec-env`, `exec-path` etc. If one of the plugins in your mega-plugin repo needed one of these scripts, then it would be executed for each plugin, not just the necessary one.

We do have _some_ plugins which manage many tools, like `hashicorp` for instance, but it is not preferrable to 1:1 plugin per tool. What happens if the `hashicorp` plugin doesn't support `consul` and the author unresponsive to PRs? Another plugin would get created that does one of the many tools and becomes confusing to users why the `hashicorp` plugin doesn't add what they expect.

Can you reconsider making separate plugins for each tool? If you want to make a parent plugin such as `vmware`, are you open to maintaining it for a long time and dealing with requests to add more support and scripts for other `vmware` tools?

**Comment by laidbackware** [comment]
@jthegedus I should have been more specific. I think that there could be a single plugin/pattern/api for generic single binary github releases, or at least covering 99% of use cases, including mine where I want to maintain support for multiple tools. In forcing unique repos for every tool (which would have 99% of common code between them) it is pushing the maintenance issue down to the developer, which will cause challenges aligning everyone when asdf changes in the future. I certainly wouldn't have invested the time in adding tools for my peers if I'd have thought I'd have to create 11 repos and maintain them separately.

On breaking my repo up. Pivotal was aquired by VMware and is no more - although the github projects continue to exist. Cloud Foundry was created by VMware, passed on to Pivotal, then spun off into a foundation. So given that is the case, I'd argue that they could all be covered under a `asdf-vmware-github-release` repo and unless the asdf repo is actually hosted under the same github project as the tools, I don't see the value in having a 1:1 relationship between asdf plugin and github project. I'd drop the other 2 tools.

I think one thing that would make a lot of sense would be to split the CI on my side so that eash tool has its own workflow which handles the tests for that plugin. Then the badge on your plugins page would reflect a failing build for that specific tool not just a failure for all tools in the repo.

From an naming perspective, just because my repo may have vmware in the name, it doesn't stop someone else from forking the repo to maintain some other VMware tools if needed. Also given the only places it is referenced in this repo is in the table on the readme and the plugin file, I'm not sure how the name of the repo should affect managability on your side. From a user's perspective, the user should be totally unaware of the repo which is sourcing their plugin, so it shouldn't cause them any confusion if one set of tools tools are partially split or co-located.

Ultimately I think there are tradeoffs everywhere. When building the plugin I looked at a lot of the github release plugins out there and there is a real mix in terms of quality, whereas they all do basically the same thing with some minor deviations. This led me to the conclusion that there should be a better way than having each github release plugin developed in isolation. What that better way is, I'm still not convinced.

**Comment by jthegedus** [comment]
>What that better way is, I'm still not convinced.

It is a question I have thought about for a long time. A better answer is yet to come to me.

**Pull request closed without merging**
