### PR TITLE
[New Plugin] pnpm

### PR DESCRIPTION
**Pull request by jonathanmorley**

### CODE REVIEW

**Comment by imbsky** [comment]
I think we can do that without using jq.
https://github.com/jonathanmorley/asdf-pnpm/blob/master/bin/list-all

**Comment by jonathanmorley** [comment]
removed the JQ dependency

**Comment by imbsky** [comment]
Nice, I will check it tonight. Thanks 🙂

**Comment by vic** [comment]
I'm merging this. Thank you ~all.

**Pull request merged**
