### PR TITLE
feat: Add jet

### PR DESCRIPTION
**Pull request by rynkowsg**
## Summary

Description:

- Tool repo URL: https://github.com/borkdude/jet
- Plugin repo URL: https://github.com/rynkowsg/asdf-jet

## Checklist

- [x] Format with `scripts/format.bash`
- [x] Test locally with `scripts/test_plugin.bash --file plugins/<your_new_plugin_name>`
- [x] Your plugin CI tests are green
  - _Tip: use the `plugin_test` action from [asdf-actions](https://github.com/asdf-vm/actions) in your plugin CI_

### CODE REVIEW

**Comment by rynkowsg** [comment]
Just updated the PR to resolve the conflict.
After the update there is CI complain for the format, but the issue was not introduced by this PR but earlier. Since [e428ecf](https://github.com/asdf-vm/asdf-plugins/commit/e428ecf9a669a78d7764404a274a7f2153a08619) all CI fail.

Can we merge this one now? @jthegedus

**Comment by rynkowsg** [comment]
I fixed also the CI build brake in the second PR.

**Comment by jthegedus** [comment]
Thanks for updating, sorry about the CI issues.

**Review by jthegedus — APPROVED** [review]

**Comment by rynkowsg** [comment]
No worries. Thanks

**Pull request merged**
