### PR TITLE
feat: ✨  add dasel

### PR DESCRIPTION
**Pull request by ghostsquad**
# Checklist

- [x] Provide a short description and link to your plugin.

- [x] Make sure you CI tests for your plugin and they are green.

      If you are using github, you might want to use the
      `plugin_test` action from [asdf-actions](https://github.com/asdf-vm/actions)

- [x] `asdf-plugins` CI sanity checks are green on your PullRequest.

      You can test locally using:

      ```bash
      ./test_plugin.sh --file plugins/PLUGIN_FILE
      ```

### CODE REVIEW

**Review by jthegedus — APPROVED** [review]

**Comment by ghostsquad** [comment]
do you know why I'm still getting this error @jthegedus ?

```
plugin https://github.com/asdf-community/asdf-dasel.git not found in repository
```

**Comment by ghostsquad** [comment]
OH NVM!... 🤦 `plugin add <plugin name> <url>`

**Comment by jthegedus** [comment]
`plugin add <plugin name> <url>` doesn't require the plugin to be in this repo. `plugin add <plugin name>` will perform a lookup, but of a local sync of this repo, so it sounds like the sync hadn't yet ocurred :thinking:

**Comment by ghostsquad** [comment]
I was running without the `<plugin name>` part. it was my mistake.

**Pull request merged**
