### PR TITLE
add poetry plugin

### LINKED ISSUE #122: [New Plug-in] Poetry
Python's Poetry: https://poetry.eustace.io/

### PR DESCRIPTION
**Pull request by crflynn**
closes #122

### CODE REVIEW

**Comment by imbsky** [comment]
Can you rewrite the `list-all` without jq? It should work without jq.

**Comment by crflynn** [comment]
Sure. My bash skills aren't great. What do you suggest I use instead?

**Comment by crflynn** [comment]
I can do it with python, since python needs to be installed anyway:

```bash
echo $(curl -s https://pypi.org/pypi/poetry/json | python -c 'from __future__ import print_function;import json,sys;response=json.load(sys.stdin);print(" ".join(list(response["releases"].keys())))')
```

Is this ok? Should be py2 and py3 compatible.

**Comment by imbsky** [comment]
Oh, I just opened a PR to do it in Bash.

**Comment by crflynn** [comment]
Ok. I'll go ahead and merge yours.

**Comment by imbsky** [comment]
It should work, but I haven't checked locally.

**Comment by crflynn** [comment]
I checked. It worked for me.

**Comment by imbsky** [comment]
Great, and the other code looks good to me.

**Comment by imbsky** [comment]
Thanks @crflynn for your contribution!

**Pull request merged**
