### PR TITLE
feat: add trivy plugin

### PR DESCRIPTION
**Pull request by zufardhiyaulhaq**
## Summary

https://github.com/zufardhiyaulhaq/asdf-trivy.git

plugin for install trivy. this plugin is using the asdf-plugins template.

## Checklist

- [x] CI tests are green. If you are using GitHub, you might want to use the `plugin_test` action from [asdf-actions](https://github.com/asdf-vm/actions)
- [x] `asdf-plugins` CI sanity checks are green on your PullRequest. Test locally with:

### CODE REVIEW

**Comment by zufardhiyaulhaq** [comment]
@jthegedus can you help check?

**Review by jthegedus — APPROVED** [review]
lgtm

**Comment by zufardhiyaulhaq** [comment]
Hi @jthegedus is the workflow error, I cannot see any error when executing from my local
```
asdf-plugins $ ./test_plugin.sh --file plugins/trivy         
Checking plugins/trivy
OK plugins/trivy
```

**Comment by jthegedus** [comment]
I've no idea either. I'll merge and if people complain we can investigate further

**Pull request merged**
