### PR TITLE
Adding yq plugin

### PR DESCRIPTION
**Pull request by sudermanjr**

### CODE REVIEW

**Comment by sudermanjr** [comment]
@imbsky Any thoughts on this PR?

**Comment by imbsky** [comment]
I’m sorry, I’m busy with my work in the real world recently, and there is no big problem if I don't merge to this repository right away, so I was thinking of reviewing this weekend. Well, I will make time to take a look during lunch break today.

**Comment by sudermanjr** [comment]
> I’m sorry, I’m busy with my work in the real world recently, and there is no big problem if I don't merge to this repository right away, so I was thinking of reviewing this weekend. Well, I will make time to take a look during lunch break today.

No worries! Sorry to bump, you've just been so quick in the past. You are correct, so take your time and review when convenient.

**Comment by imbsky** [comment]
Thanks for your kind words 🙂

**Comment by vic** [comment]
LGTM, I'll merge this. Thanks @sudermanjr.

**Comment by imbsky** [comment]
Thanks @vic

**Comment by vic** [comment]
No problemo. :)

**Pull request merged**
