### PR TITLE
Cleanup README.md

### PR DESCRIPTION
**Pull request by imbsky**

### CODE REVIEW

**Comment by imbsky** [comment]
The old one was too chaotic...

**Comment by imbsky** [comment]
https://raw.githubusercontent.com/asdf-vm/asdf-plugins/88d75cbedd07dcf4416239c69cbdba406daa0e0f/README.md

**Comment by imbsky** [comment]
Probably prettier is the good solution. But this PR is only cleanup README.

**Comment by Stratus3D** [comment]
I don't think the changes to the formatting of the plugin table improves the code. I can't view the rows of the table on a single line either way, so I think leaving the table the way it was is best, simply because both are hard to read and the existing lines are shorter and therefore easier to trace across multiple lines when necessary.

Wrapping the text at 80 columns like you have done looks good though, happy to merge those changes.

**Comment by imbsky** [comment]
or I can re-write this huge list with macro.

**Comment by imbsky** [comment]
@Stratus3D Updated.

**Comment by Stratus3D** [comment]
@imbsky thanks!

**Pull request merged**
