### PR TITLE
chore: change HashiCorp plugins

### PR DESCRIPTION
**Pull request by nikolay**
## Summary

All the HashiCorp plugins were moved under https://github.com/asdf-community so I switched to the proper repositories, build status, and replaced `terraform-ls` and `Levant` to use the community repository instead.

## Checklist

- [x] CI tests are green. If you are using GitHub, you might want to use the `plugin_test` action from [asdf-actions](https://github.com/asdf-vm/actions)
- [x] `asdf-plugins` CI sanity checks are green on your PullRequest. Test locally with:

```bash
./test_plugin.sh --file plugins/boundary
./test_plugin.sh --file plugins/consul
./test_plugin.sh --file plugins/levant
./test_plugin.sh --file plugins/nomad
./test_plugin.sh --file plugins/packer
./test_plugin.sh --file plugins/sentinel
./test_plugin.sh --file plugins/serf
./test_plugin.sh --file plugins/terraform
./test_plugin.sh --file plugins/terraform-ls
./test_plugin.sh --file plugins/vault
./test_plugin.sh --file plugins/waypoint
```

### CODE REVIEW

**Comment by nikolay** [comment]
The repository https://github.com/Banno/asdf-hashicorp was transferred to https://github.com/asdf-community/asdf-hashicorp long ago and has abandoned the Travis CI builds, so, I updated the build status badges as well.

**Comment by nikolay** [comment]
BTW, the new `tfc-agent` plugin is supported only on Linux as HashiCorp does not release artifacts for other platforms.

**Comment by jthegedus** [comment]
> BTW, the new `tfc-agent` plugin is supported only on Linux as HashiCorp does not release artifacts for other platforms.

Plugin authors can program pre & post hooks to check the users OS and alert them to these types of issues.

**Review by jthegedus — APPROVED** [review]
Thanks very much

**Comment by jthegedus** [comment]
I will note, for some of these, the community maintained solution might not be better in that it is a generic solution for many tools and the tool-specific solutions might be better for reasons I do not yet know.

Nonetheless, people will raise them if need be.

**Comment by nikolay** [comment]
@jthegedus Thanks for merging! I did check the non-[`asdf-community`](https://github.com/asdf-community) solutions - they were not better written or maintained. For example, I submitted a PR against the https://github.com/asdf-community/asdf-hashicorp and it was reviewed, merged, and released within a couple of hours and the codebase (which I started 3+ years ago, by the way) is battle-tested.

With the growing number of supply-chain attacks, credibility is especially important and https://github.com/asdf-community is more credible than a few random developers who could inject malicious Bash script on my machine by intent or by being hacked.

Ideally, all plugins that you provide out of the box need to be forked under https://github.com/asdf-community and each upstream change should be reviewed for malicious injections. Of course, it's a lot more work, but it also reduces the responsibility behind listing a non-verifiable plugin. Meanwhile, people can still add non-community on their own risk plugins if they decide to!

**Comment by jthegedus** [comment]
These reasons you list is why we want to move away from a model that uses this plugin-repo and more to a search model. The asdf-community isn't managed by the asdf core team, though we appreciate their support. Additionally, though we do have some plugins under the asdf GitHub org, these shouldn't be considered first-party, they were simply started by core maintainers, I personally am in favour of moving those outside of the asdf GitHub org, but that's another discussion.

Thanks for reviewing this and providing feedback, much appreciated.

**Pull request merged**
