### PR TITLE
fix: remove asdf-heptio-authenticator-aws

### PR DESCRIPTION
**Pull request by joschi**
The Heptio AWS Authenticator (https://github.com/heptio/authenticator) has been migrated/promoted to the official Kubernetes AWS IAM Authenticator (https://github.com/kubernetes-sigs/aws-iam-authenticator) which is already available via `asdf-aws-iam-authenticator` (https://github.com/stefansedich/asdf-aws-iam-authenticator).

Additionally `asdf-heptio-authenticator-aws` is currently broken because it doesn't follow HTTP redirects to the new repository URL.

```
> asdf list-all heptio-authenticator-aws
+ set -e
+ set -o pipefail
+ releases_path=https://api.github.com/repos/heptio/authenticator/releases
+ cmd='curl -s'
+ '[' -n '' ']'
+ cmd='curl -s https://api.github.com/repos/heptio/authenticator/releases'
++ eval curl -s https://api.github.com/repos/heptio/authenticator/releases
+++ curl -s https://api.github.com/repos/heptio/authenticator/releases
++ grep -oE 'tag_name":\s*".{1,15}",'
++ sed 's/tag_name\": *\"v//;s/\",//'
++ sort_versions
++ sed 'h; s/[+-]/./g; s/.p\([[:digit:]]\)/.z\1/; s/$/.z/; G; s/\n/ /'
++ LC_ALL=C
++ sort -t. -k 1,1 -k 2,2n -k 3,3n -k 4,4n -k 5,5n
++ awk '{print $2}'
+ versions=

> curl -s https://api.github.com/repos/heptio/authenticator/releases
{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/99036030/releases",
  "documentation_url": "https://docs.github.com/v3/#http-redirects"
}
```

CC: @neerfri

### CODE REVIEW

**Comment by smorimoto** [comment]
Have you talked to @neerfri about this?

**Comment by smorimoto** [comment]
And if it's used in some workflow, I don't think we can delete it. ​For example, if it's used in CI workflow, it may cause the workflow to fail.

**Comment by joschi** [comment]
> Have you talked to @neerfri about this?

No, that's why I've mentioned him in this PR, too. 😃

> And if it's used in some workflow, I don't think we can delete it. ​For example, if it's used in CI workflow, it may cause the workflow to fail.

Fair point, but consider that at the moment the plugin doesn't work and will always provide no versions to install (`list-all` returns an empty list).

A PR to at least follow redirects has been open since August 2019: https://github.com/neerfri/asdf-heptio-authenticator-aws/pull/1

**Comment by jthegedus** [comment]
Can we get a resolution on this?

**Comment by joschi** [comment]
I've contacted @neerfri via email and asked him to chime in here.

I cannot fix the failing workflow because it only checks for newly added plugins but doesn't seem to handle removed plugins quite right.

**Comment by neerfri** [comment]
Hi, apologies for the radio silence.
I think it's OK to delete this, if some workflow fails due to this it's a good time to fix the workflow ;-)

Thanks!

**Review by jthegedus — APPROVED** [review]

**Comment by jthegedus** [comment]
Let's force some people to fix their workflows ;)

**Pull request merged**
