### PR TITLE
Add Helm Chart Releaser plugin

### PR DESCRIPTION
**Pull request by Antiarchitect**

### CODE REVIEW

**Comment by imbsky** [comment]
The code looks good. Can you make the repository name a little easier to understand? For example, asdf-chart-releaser is not bad.

**Comment by Antiarchitect** [comment]
> The code looks good. Can you make the repository name a little easier to understand? For example, asdf-chart-releaser is not bad.

Will asdf-helm-cr be good? As the chart releaser is one small tool for the bigger tool called Helm and we already have asdf-helm.

**Comment by imbsky** [comment]
That name sounds good to me!

**Comment by Antiarchitect** [comment]
@imbsky I've fixed the repo name

**Comment by imbsky** [comment]
Can you re-enable Travis? or testing with GitHub Actions is a good idea.

**Comment by imbsky** [comment]
I opened a PR for your repository, but if you want to continue using Travis, feel free to close it.

**Comment by Antiarchitect** [comment]
All merged. Thank you for your commitment ^_^

**Comment by imbsky** [comment]
Thanks @Antiarchitect for your contribution!

**Pull request merged**
