### PR TITLE
feat: introduce conftest, dive, hadolint, k9s, kube-capacity, kubectl-bindrole, promtool, rbac-lookup, reg, stern, terraform-docs and velero

### PR DESCRIPTION
**Pull request by looztra**
| Language  | Repository  | CI Status
|-----------|-------------|----------
| conftest | [looztra/asdf-conftest](https://github.com/looztra/asdf-conftest) | [Build Status](https://travis-ci.org/looztra/asdf-conftest)
| dive | [looztra/asdf-dive](https://github.com/looztra/asdf-dive) | [Build Status](https://travis-ci.org/looztra/asdf-dive)
| hadolint | [looztra/asdf-hadolint](https://github.com/looztra/asdf-hadolint) | [Build Status](https://travis-ci.org/looztra/asdf-hadolint)
| k9s       | [looztra/asdf-k9s](https://github.com/looztra/asdf-k9s) | [Build Status](https://travis-ci.org/looztra/asdf-k9s)
| kube-capacity | [looztra/asdf-kube-capacity](https://github.com/looztra/asdf-kube-capacity) | [Build Status](https://travis-ci.org/looztra/asdf-kube-capacity)
| kubectl-bindrole       | [looztra/asdf-kubectl-bindrole](https://github.com/looztra/asdf-kubectl-bindrole) | [Build Status](https://travis-ci.org/looztra/asdf-kubectl-bindrole)
| promtool | [looztra/asdf-promtool](https://github.com/looztra/asdf-promtool) | [Build Status](https://travis-ci.org/looztra/asdf-promtool)
| rbac-lookup       | [looztra/asdf-rbac-lookup](https://github.com/looztra/asdf-rbac-lookup) | [Build Status](https://travis-ci.org/looztra/asdf-rbac-lookup)
| reg       | [looztra/asdf-reg](https://github.com/looztra/asdf-reg) | [Build Status](https://travis-ci.org/looztra/asdf-reg)
| stern | [looztra/asdf-stern](https://github.com/looztra/asdf-stern) | [Build Status](https://travis-ci.org/looztra/asdf-stern)
| terraform-docs | [looztra/asdf-terraform-docs](https://github.com/looztra/asdf-terraform-docs) | [Build Status](https://travis-ci.org/looztra/asdf-terraform-docs)
| velero | [looztra/asdf-velero](https://github.com/looztra/asdf-velero) | [Build Status](https://travis-ci.org/looztra/asdf-velero)

### CODE REVIEW

**Comment by Stratus3D** [comment]
@looztra is there any way you could break this up into individual PRs? I rarely have more than 15 minutes to review plugin PRs for this repo, and I won't be able to review all the code in these plugins in 15 minutes.

**Comment by looztra** [comment]
yep, no prob

**Comment by looztra** [comment]
closing, see #106 #107 #108 #109 #110 #111 #112 #113 #114 #115 #116 #117 #118

**Comment by Stratus3D** [comment]
Thanks for taking the time to split this PR up! It might take me a while to review them all, but I will.

**Pull request closed without merging**
