### PR TITLE
Separate plugin list

### PR DESCRIPTION
**Pull request by sakuro**
This is my idea to #84.

This PR separates the plugin list into two, one for test-passing plugins and one for test-failing plugins.  And exit status of the test.sh is now count of previously passing but become failing ones.

The benefit is that we can merge PRs (mainly ones which add innocent new plugins) without waiting broken plugins be fixed.

### CODE REVIEW

**Comment by imbsky** [comment]
Are you still interested in working on this? I'm willing to review that.

**Comment by Stratus3D** [comment]
I think it would make more sense to just remove failing plugins entirely if they have failing builds after a certain amount of time.

**Comment by Stratus3D** [comment]
What is the benefit of displaying a list of plugins with failing builds?

**Comment by imbsky** [comment]
It certainly makes sense, this list needs to be a list of high quality plugins, and those that fail testing don't need to be listed.

**Pull request closed without merging**
