### PR TITLE
add plugin for jb (jsonnet-bundler)

### PR DESCRIPTION
**Pull request by yogeek**
This PR adds a plugin for jb ([jsonnet-bundler](https://github.com/jsonnet-bundler/jsonnet-bundler))

The CI is green : [GitHub Actions Status](https://github.com/beardix/asdf-jb/actions) 

Thanks @beardix for the plugin !

### CODE REVIEW

**Comment by yogeek** [comment]
@imbsky it seems that the CI job is failing because of these plugins but not the one I want to add :
```
Plugin build check failed:  https://travis-ci.org/asdf-vm/asdf-erlang
Plugin build check failed:  https://travis-ci.org/vic/asdf-haskell
Plugin build check failed:  https://travis-ci.org/halcyon/asdf-java
Plugin build check failed:  https://travis-ci.org/rkyleg/asdf-julia
Plugin build check failed:  https://travis-ci.org/sylph01/asdf-mongodb
Plugin build check failed:  https://travis-ci.org/asdf-vm/asdf-nodejs
```

How can you validate that only the plugin ci concerned by the PR only is ok ?
Thanks

**Comment by imbsky** [comment]
Could you resolve a conflict?

**Comment by imbsky** [comment]
and CI isn't working now so you don't have to worry about it.

**Comment by yogeek** [comment]
@imbsky what conflict...?

**Comment by imbsky** [comment]
I was talking about this. https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-merge-conflicts
But now I have resolved it.

**Comment by imbsky** [comment]
Thanks @yogeek.

**Pull request merged**
