### PR TITLE
Add etcd plugin

### PR DESCRIPTION
**Pull request by particledecay**
Current build status: Build Status

### CODE REVIEW

**Comment by Stratus3D** [comment]
The name here is a little confusing, and I'm not sure if this plugin supports all of etcd or just `etcdctl`. Is there a reason this is named `asdf-etcdctl` instead of `asdf-etcd`? Plugins should be named after the tool they are managing (`etcd` in this case) not the actual command. For example, we have `asdf-postgres`, not `asdf-psql`.

Perhaps this is something I should clarify in the docs.

**Comment by particledecay** [comment]
I see... I'm not married to the name. I can change it. Etcd doesn't provide just the binary so I had to pull it from the main repo, which is why I chose that name. But what you said makes sense.

**Comment by particledecay** [comment]
Actually now that I'm thinking about it, we also have asdf-kubectl rather than asdf-kubernetes. I think we have it both ways. I'd say this is closer to kubectl -> kubernetes than it is to psql -> postgres.

I also submitted another PR that was asdf-osctl instead of asdf-talos. I'm not 100% sure which way to go on this and I can see the argument for both.

**Comment by Stratus3D** [comment]
I'd rather see things like asdf-talos instead of asdf-osctl now that I think about it. asdf-talos just seems like a more recognizable and descriptive name to me. I'm open discussing this though. @asdf-vm/plugins what do you all think?

**Comment by particledecay** [comment]
happy to follow the consensus on this one

**Comment by particledecay** [comment]
So, as a follow-up, I'm seeing a potential naming issue with my latest PR (#138). My plugin installs the RKE tool that Rancher uses for installations and configuration. However, there's already an "asdf-rancher". That one installs the specific "rancher" tool that manages their software.

So then there are three potential avenues I can see here:
1) plugins are named for the specific tool they install (osctl vs talos, etcdctl vs etcd, rke vs rancher)
2) plugins are named for the application they are managing
3) plugins are named for the application they are managing, AND you can install all of the tools for that application (rancher AND rke, for instance)

**Comment by Stratus3D** [comment]
@particledecay not sure about rancher and RKE. I'd say that generally if two things can be used and versioned independently (or independently to a certain degree) then it's fine to have two plugins. But if things conflict with each other (e.g. provide the same commands) or have hard dependencies on each other that prevents them from being versioned independently (e.g. they must both be the exact same version) then I think it makes sense to combine them and only permit one or the other.

A good example of this is Erlang and Rebar. They are independent projects (or at least they have been, that may be changing) that can be versioned independently. Rebar is a build tool for Erlang, so it only makes sense to use it when Erlang is present, but it's separate enough that versioning them separately can make sense.

I'm not sure how this fits in with Rancher and RKE.

**Comment by Stratus3D** [comment]
And as far as naming goes. I'd recommend naming plugins after the tool/application/project they install. And when possible a plugin should manage everything that tool/application/project offers. So for projects that provide multiple commands, the plugin should support all of them. But it doesn't have to support plugins and other related tools/applications/projects.

Not sure if that makes sense.

**Comment by particledecay** [comment]
No, that makes sense. I get where you're trying to go with this and I think for the most part I agree with you. For context, Rancher has a separately versioned [RKE](https://github.com/rancher/rke) tool that installs Kubernetes on target systems. It also handles installation of the Rancher software (I believe).

That Rancher software (their bread and butter) manages Kubernetes clusters for you, and you can interact with the software through that command-line "rancher" tool.

So, they are separately versioned, but it probably wouldn't make sense to use RKE unless you also plan on using the Rancher software. I'm not that good with Rancher (yet) so I'm mostly guessing here (who knows, maybe you can still use RKE and not install the Rancher software?), but I'm giving you the context as I currently understand it.

Anyway wasn't looking to derail the conversation, but from a contribution perspective... I could always just rename this to etcd instead, since this may relate to `psql -> postgres` usage.

**Comment by Stratus3D** [comment]
I think renaming this to `etcd` is best for now. You don't necessarily have to rename your repo, but I think `etcd` is the right name for the plugin.

**Comment by particledecay** [comment]
ok no problem, I'll do that and resubmit

**Comment by imbsky** [comment]
@particledecay Can you rebase this?

**Comment by particledecay** [comment]
Sure I'll look at doing that tonight

**Comment by imbsky** [comment]
Thanks!

**Comment by imbsky** [comment]
@Stratus3D What do you think? This looks good to me now.

**Comment by Stratus3D** [comment]
Looks good to me. Thanks @particledecay!

**Pull request merged**
