### PR TITLE
Add joschi/asdf-mvnd

### PR DESCRIPTION
**Pull request by joschi**
## Description

[mvnd](https://github.com/mvndaemon/mvnd) plugin for asdf-vm: https://github.com/joschi/asdf-mvnd

## Checklist

- [x] Provide a short description and link to your plugin.
- [x] Make sure you CI tests for your plugin and they are green.

      If you are using github, you might want to use the
      `plugin_test` action from [asdf-actions](https://github.com/asdf-vm/actions)

- [x] `asdf-plugins` CI sanity checks are green on your PullRequest.

      You can test locally using:

      ```bash
      ./test_plugin.sh --file plugins/mvnd
      ```

### CODE REVIEW

**Comment by smorimoto** [comment]
Is this needed?
https://github.com/joschi/asdf-mvnd/blob/84d77a1c3bef0cabd58eea9dcd99b610d364021a/bin/list-all#L3

**Comment by smorimoto** [comment]
Overall, it looks like a little redundant code, but it doesn't have a major problem and looks good!

**Review by smorimoto — APPROVED** [review]

**Comment by joschi** [comment]
@smorimoto Thanks for the hint! I've removed the unnecessary readonly variable in the `list-all` script.

FWIW, I've taken some inspiration from https://github.com/asdf-community/asdf-arkade/blob/d314d9a673c7c2bdcf5b7b7a99a2635a6e579ccb/bin/list-all#L3 for the `list-all` script. 😉 

If there are coding guidelines for asdf-vm plugins, I'd be happy if you could point me to them.

**Comment by smorimoto** [comment]
There are no coding guidelines. Also, as far as I've reviewed, I don't see any asdf-specific problems in the plugin code in many cases, and I don't think we will need them. Well, it's not a bad idea to look at the community repositories, but many repositories are still in the improvement phase and we don't have enough bandwidth to do it yet...

**Comment by smorimoto** [comment]
Anyway, thanks @joschi!

**Pull request merged**
