### PR TITLE
Change default sbt plugin to gabrielelana/asdf-sbt

### PR DESCRIPTION
**Pull request by sciamp**
Fixes asdf-vm/asdf-plugins#70

### CODE REVIEW

**Comment by Stratus3D** [comment]
This PR has already been merged - https://github.com/asdf-vm/asdf-plugins/pull/53

**Comment by Stratus3D** [comment]
Thank you for taking the time to create this PR though.

**Comment by sciamp** [comment]
> Thank you for taking the time to create this PR though.

Sorry mate didn't mean to duplicate the issue and the PR :)

Thanks for you time,
sciamp

**Comment by Stratus3D** [comment]
No worries, I've fallen behind on reviewing these PRs.

**Pull request closed without merging**
