### PR TITLE
feat: plugins from chessmango for aws, charm et al

### PR DESCRIPTION
**Pull request by chessmango**
## Summary

Adds plugins for awsls, awsrm, awsweeper, flyctl, hcloud, hwatch, iamlive, jiq, redo, terradozer, zellij, glow, melt, skate, soft-serve, vhs. Bumper :P

## Checklist

- [X] CI tests are green. If you are using GitHub, you might want to use the `plugin_test` action from [asdf-actions](https://github.com/asdf-vm/actions)
- [X] `asdf-plugins` CI sanity checks are green on your PullRequest. Test locally with:

```bash
./test_plugin.sh --file plugins/<PLUGIN_FILE>
```

### CODE REVIEW

**Comment by jthegedus** [comment]
Wow, you've been busy!

**Comment by chessmango** [comment]
> Wow, you've been busy!

:sweat_smile: Nice folks at Charm (mostly) stick to the same packaging/naming conventions, which helps. The rest are pre-existing, just have left out of this repo.

Considering CI's expecting a single plugin per PR, should I go ahead and split this up? :P

**Comment by jthegedus** [comment]
>should I go ahead and split this up

No need to do that, I will review and it'll likely be fine.

**Review by jthegedus — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
