### PR TITLE
fix: Update azure-cli python dependency

### PR DESCRIPTION
**Pull request by fragolinux**
forced and fixed python version 3.10.11

## Summary

Description:

- Tool repo URL: https://github.com/Azure/azure-cli
- Plugin repo URL: https://github.com/EcoMind/asdf-azure-cli

## Checklist

- [X] Format with `scripts/format.bash`
- [X] Test locally with `scripts/test_plugin.bash --file plugins/<your_new_plugin_name>`
- [X] Your plugin CI tests are green
  - _Tip: use the `plugin_test` action from [asdf-actions](https://github.com/asdf-vm/actions) in your plugin CI_

### CODE REVIEW

**Comment by jthegedus** [comment]
Changing plugins from one repo to another is something we want to avoid if at all possible.

It would be great if you could link an open issue on the original repo showing that this change has tried to be added upstream and ignored after some time, that it is blocking a large number of users, or that the maintainer is inactive or unresponsive.

Also, changes would need to be made for this entry in the README file.

Thanks.

**Comment by fragolinux** [comment]
The original repo is archived and not maintenaid anymore, as the author does not use the tool anymore, since last November... Does not work if using python 3.11, so we fixed a python version 3.10, using asdf itself, inside our fork...

**Comment by fragolinux** [comment]
@jthegedus 

hi fixed the readme, pointing to our repo, and for the other things you asked, I already replied above (and [here](https://github.com/asdf-vm/asdf-plugins/commit/d2fea9e449f597cf0999f14fe12b94fcef79ab9e) where you did the same on the jq plugin, just a few days ago)

**Review by jthegedus — APPROVED** [review]

**Comment by jthegedus** [comment]
>P.S. Changing a repo is something that you did just a few days ago, on the JQ plugin 😉

Yes, and there was discussion in that thread from many people about the existing plugin and it's lack of support. This thread is just you raising it. The additional information you provided was what I was after, thanks.

**Pull request merged**
