### PR TITLE
Add plugin entry

### PR DESCRIPTION
**Pull request by samtgarson**
Adds [1password CLI](https://1password.com/downloads/command-line/) version management.

### CODE REVIEW

**Comment by Stratus3D** [comment]
Is this something users actually need to run multiple versions of? I know we have a bitwarden plugin, but I'm curious why users will need to have multiple versions of this installed.

**Comment by Stratus3D** [comment]
Code looks good though, so no objections to merging this from a technical standpoint.

**Comment by samtgarson** [comment]
Fair question—to be honest personally I've found asdf just as useful for keeping libraries that aren't available on standard package managers up to date on multiple OS's, especially when they're under active development (like this one is).

Understand that that's not this tool's primary use though, so happy to keep it as an "unofficial" plugin if you'd prefer.

**Comment by Stratus3D** [comment]
@samtgarson I'm fine with it for now. If we decide to pare down the plugin list in the future we may remove it.

**Pull request merged**
