### PR TITLE
docs: explicitly state no security for this repo

### PR DESCRIPTION
**Pull request by jthegedus**
## Summary

Explicitly state that asdf does not provide security policy for the plugins listed in this repo.

### CODE REVIEW

**Comment by aabouzaid** [comment]
Yeah, I was about to mention that.
asdf is great, but all plugins are not secure by design.

**Comment by jthegedus** [comment]
>all plugins are not secure by design
I do not know of a single system that has OSS plugin model where the plugins are considered secure.

**Comment by aabouzaid** [comment]
@jthegedus I believe that the feature in https://github.com/asdf-vm/asdf/pull/916 should metigate that by setting the git ref (especially the hash) to make sure the users will get exactly what they expected.

There will always be a security risk, we just need to make the flow more secure :-)

**Comment by jthegedus** [comment]
Yeah, I really need to update https://github.com/asdf-vm/asdf/pull/1204 which has the latest solve for that.

**Comment by jthegedus** [comment]
@Stratus3D do you think this is acceptable?

**Pull request merged**
