### PR TITLE
Change sbt plugin repository

### PR DESCRIPTION
**Pull request by andys8**
## Issue
There is an open issue to support newer versions in the currently used plugin repository: https://github.com/lerencao/asdf-sbt/pull/2 Currently not being resolved

### Possible solution
There is https://github.com/gabrielelana/asdf-sbt 
It supports the newer 1.x.x versions for releases since [Aug. 2017](https://developer.lightbend.com/blog/2017-08-11-sbt-1-0-0/).

```shell
$ asdf list-all sbt                                                                   1076ms
1.0.0
1.0.0-RC2
1.0.0-RC3
1.0.1
1.0.2
1.0.3
1.0.4
1.1.0
1.1.0-M1
1.1.0-RC1
1.1.0-RC2
1.1.0-RC3
1.1.0-RC4
1.1.1
1.1.2
1.1.3
1.1.4
1.1.5
1.1.6
1.2.0
1.2.0-M1
1.2.0-RC1
1.2.0-RC2
1.2.0-RC3
1.2.1
1.2.2
1.2.3
1.2.4
1.2.5
1.2.6
```
### Alternative
An alternative solution would be to port the changes to the current repository, which would need a maintainer.

Mentions for awareness :) @lerencao @gabrielelana

### CODE REVIEW

**Comment by lerencao** [comment]
It would be great that someone can supports on this.
I had escaped from sbt world long time ago.  :)

**Comment by andys8** [comment]
@lerencao Thanks for feedback. I found out, the `README` has to be updated, and I appended the change.

**Comment by andys8** [comment]
Travis is not failing plugin `sbt`

**Comment by Stratus3D** [comment]
Thanks for the PR @andys8 ! This seems like the right approach.

**Pull request merged**
