### PR TITLE
Updated R plugin reference to an updated fork

### PR DESCRIPTION
**Pull request by taiar**
I had to update my R installation for R4 and the default asdf plugin for it was not updated for a long time. I decided to fork and update it to support the latest major versions and I'm sending this update now.

This is the link for the updated plugin: https://github.com/taiar/asdf-R

This PR also fixes issue #274

### CODE REVIEW

**Comment by smorimoto** [comment]
FYI: @iroddis

**Review by jthegedus — APPROVED** [review]
Approving and merging for now, we can update again depending on how merging this plugin into the asdf-community repo as discussed in #274

**Comment by iroddis** [comment]
Gah! I wasn't getting any notifications of all the PRs on the original plugin. Thanks for the updates, @taiar . I merged in some outstanding PRs, and there may be some documentation in there that would be useful in your version (using asdf-R with RStudio, etc). I don't mind if you want to take over.

Sorry to everyone who was waiting on the original to support v4. Not sure why I wasn't getting notified.

**Comment by taiar** [comment]
Thank you @smorimoto, @jthegedus, and @iroddis!

@iroddis, I did pick all of the PR suggestions that were on your repo to build the version I published. 

You can see there is a section about building the R shared lib to support Rstudio and Cairo lib https://github.com/taiar/asdf-R#building-r-shared-library

I might make some more improvements if it is ok for me to take over, and, sure, I'll be glad.

**Pull request merged**
