### PR TITLE
add HashiCorp Boundary

### PR DESCRIPTION
**Pull request by radditude**
# Checklist

- [x] Provide a short description and link to your plugin.

The HashiCorp tooling plugin at https://github.com/Banno/asdf-hashicorp supports [Boundary](https://www.boundaryproject.io/), but it isn't listed here yet.

- [x] Make sure you CI tests for your plugin and they are green.

Boundary is already supported by the plugin, but you don't have to take my word for it! https://github.com/Banno/asdf-hashicorp/pull/16 adds tests to verify continued support going forward.

- [x] `asdf-plugins` CI sanity checks are green on your PullRequest.

### CODE REVIEW

**Comment by smorimoto** [comment]
@radditude Thanks for opening the PR. It looks good overall, but I would like to add some changes to the upstream. Can you wait for that?

**Comment by radditude** [comment]
Certainly! No rush 😄

**Comment by smorimoto** [comment]
Let's merge once. Their response is very slow.

**Review by smorimoto — APPROVED** [review]

**Comment by radditude** [comment]
Awesome! I'll make followup PRs if the plugin URL does change in the future.

**Comment by smorimoto** [comment]
Thank you!

**Pull request merged**
