### PR TITLE
Swap rfrancis/asdf-nim for asdf-community/asdf-nim

### PR DESCRIPTION
**Pull request by elijahr**
# Checklist

[Build Status](https://github.com/asdf-community/asdf-nim/actions)

- [x] Provide a short description and link to your plugin.

- [x] Make sure you have CI tests for your plugin and they are green. 

- [x] `asdf-plugins` CI sanity checks are green on your pull request.

## Other Information

The current plugin listed for Nim, [rfrancis/asdf-nim](https://github.com/rfrancis/asdf-nim/blob/master/bin/install) is unmaintained (author is looking for a maintainer and suggests they are fine with another plugin being listed - see [#11](https://github.com/rfrancis/asdf-nim/issues/11#issuecomment-703979142)). I've written an alternative plugin with features that I think that community would benefit from. I'd love to have my plugin officially listed for Nim.

Features in [asdf-community/asdf-nim](https://github.com/asdf-community/asdf-nim):
- Subcommand to install plugin dependencies
- Installs binaries rather than building from source in most common use-cases
- Each version of Nim gets its own nimble package dir, rather than a shared global one
- Faster builds from source via reusing existing nims for bootstraping

### CODE REVIEW

**Comment by smorimoto** [comment]
What about maintaining it in the asdf-community for the future?
https://github.com/asdf-community

**Comment by elijahr** [comment]
> What about maintaining it in the asdf-community for the future?
> https://github.com/asdf-community

Sure, I'd be happy to move my plugin there. If somebody creates an `asdf-plugin-nim` repository in that organization I'll make a pull request with my plugin's code.

**Comment by smorimoto** [comment]
@elijahr Done. Feel free to push the code.

**Comment by elijahr** [comment]
@smorimoto I pushed my plugin to asdf-community/asdf-nim and have updated this PR to reflect that. 

Looks like GitHub set the default branch for asdf-community/asdf-nim to `migrate-to-asdf-community`. I don't have permissions to change the default branch for that repository. Could you give me those permissions or change the default branch for me to either `main` (preferred) or `master`?

**Comment by smorimoto** [comment]
Updated as Main. Note that using `v1` is a better choice for the asdf action's version. Also, since the `github_token` input is not required, and the action tests the latest version by default, so I don't think it's a bad idea to add a job to test the latest version with cron.

**Comment by smorimoto** [comment]
This is a good way to know early on that an unexpected upstream change will break our plugin.

**Comment by elijahr** [comment]
@smorimoto thank you for the feedback! I've implemented it in https://github.com/asdf-community/asdf-nim/pull/1 if you want to take a look. Otherwise I'll just merge it once the builds are green. Thanks!

**Comment by smorimoto** [comment]
Great! Thanks.

**Comment by smorimoto** [comment]
I think this PR can be merged.

**Review by smorimoto — APPROVED** [review]

**Comment by smorimoto** [comment]
Thanks @elijahr!

**Comment by elijahr** [comment]
Thank you!

**Pull request merged**
