### PR TITLE
feat: add go-sdk plugin

### PR DESCRIPTION
**Pull request by yacchi**
## Summary

[asdf-go-sdk](https://github.com/yacchi/asdf-go-sdk) install SDK of [Go](https://golang.org/)

The Go plugin [asdf-golang] already exists. However, the plugin is installed and handled for SDK differently from commonly used development environments (e.g. VSCode or JetBrains IDE), so you need to manage the SDK twice.

This plugin installs the SDK using Go's [official installation method], so it can share the SDK and cache with these development environments.
It has the advantage of saving disk space and faster builds when working in both the IDE and the terminal.

## Checklist

- [x] Make sure you CI tests for your plugin and they are green.
      The plugin generated from [asdf-vm/asdf-plugin-template](https://github.com/asdf-vm/asdf-plugin-template), and all Actions are currently green.
[Build](https://github.com/yacchi/asdf-go-sdk/actions/workflows/build.yml) [Lint](https://github.com/yacchi/asdf-go-sdk/actions/workflows/lint.yml)

- [x] `asdf-plugins` CI sanity checks are green on your PullRequest. Test locally with:
      Local checks have been successful.

```
> ./test_plugin.sh --file plugins/go-sdk 
Checking plugins/go-sdk
OK plugins/go-sdk
```

[asdf-golang]: https://github.com/kennyp/asdf-golang
[official installation method]:https://golang.org/doc/manage-install#installing-multiple

### CODE REVIEW

**Comment by jthegedus** [comment]
Would someone using this plugin need to install and manage the existing plugin as well, or does this plugin do what the existing plugin does plus the new SDK stuff?

**Comment by yacchi** [comment]
No, it's not. This plugin is not dependent on any existing plugins. This plugin does not depend on any existing plugins, and you can build a Go development environment by itself.

I had no problem installing it at the same time as existing plugins, especially asdf-golang (of course, if you set the same version, only one of them will be available).

I considered making contributions to the existing plugins, but the design principles are very different.

**Comment by jthegedus** [comment]
Sorry for the questions, just trying to clarify how this is different.

So this new plugin does everything the existing one, but is just installed differently exposing expected config to IDEs? Is that correct?

**Comment by yacchi** [comment]
There are other differences besides the installation method. Basically, this plugin prefers to follow the standard Go language method, so it works differently from the normal asdf plugin in some ways.

- Install the SDK under `HOME/sdk`

The SDKs installed by this plugin are stored by version under `HOME/sdk`, and a symbolic link is created under asdf/installs.

If the plugin saves it under asdf/installs, the SDK may not be available from the IDE, in which case the user will have to save it under `HOME/sdk` as well.  The SDK is several hundred MB/version.

Set up the SDK in a way other than asdf, it may not be visible to asdf. In this case, can use `asdf go-sdk sync` to sync `HOME/sdk` and asdf/installs.

If asdf has a `list hook`, can do sync every time you want to show the list, so that you don't need this command (sync usually takes less than a second).

- GOPATH is not changed.

The Go language downloads dependent library sources, pre-built libraries, etc. under the GOPATH.
When building a program written in Go, the Go compiler will automatically download the dependent libraries under this directory and build it.

If the plugin separates the GOPATH into different versions, it will download the libraries for each version of Go.
Since IDEs do not support this, the dependency libraries seen from the terminal and the ones seen from the IDE are different, which may cause problems.

- Do not change GOPATH/bin or GOBIN

The Go language allows you to install command-line tools with `go get` or `go install` (1.17 or later).
 Installed programs do not have any dependency on the SDK, so you do not need to manage them together with the SDK, unlike Python and other languages.

**Comment by jthegedus** [comment]
Okay, thanks for sharing.

**Pull request merged**
