### PR TITLE
feat: shellspec plugin

### PR DESCRIPTION
**Pull request by poikilotherm**
See https://github.com/shellspec/shellspec for details on ShellSpec.
Plugin at https://github.com/poikilotherm/asdf-shellspec allows for easy install with ASDF.

# Checklist

- [X] Provide a short description and link to your plugin.
- [X] Make sure you CI tests for your plugin and they are green.
- [x] `asdf-plugins` CI sanity checks are green on your PullRequest.

      You can test locally using:

      ```bash
      ./test_plugin.sh --file plugins/PLUGIN_FILE
      ```

## Other Information

If there is anything else that is relevant to your pull request include that
information here.

Thank you for contributing to asdf-plugins!

### CODE REVIEW

**Comment by ghostsquad** [comment]
@poikilotherm can you rebase resolve the conflict with the readme? I think this would allow this be merged.

**Comment by jthegedus** [comment]
It is also a good idea to look at https://github.com/asdf-vm/asdf-plugin-template for formatting, ci checks, configs etc that we hope to align all plugins on

**Comment by poikilotherm** [comment]
@ghostsquad done :smile: 
@jthegedus migrated. :smiley:

**Review by jthegedus — APPROVED** [review]

**Comment by jthegedus** [comment]
Thanks mate

**Pull request merged**
