### PR TITLE
feat: add stratus-red-team plugin

### PR DESCRIPTION
**Pull request by vthiery**
## Summary

Description:

- Tool repo URL: https://github.com/DataDog/stratus-red-team
- Plugin repo URL: https://github.com/vthiery/asdf-stratus-red-team

## Checklist

- [x] Format with `scripts/format.bash`
- [x] Test locally with `scripts/test_plugin.bash --file plugins/stratus-red-team`
- [x] Your plugin CI tests are green
  - _Tip: use the `plugin_test` action from [asdf-actions](https://github.com/asdf-vm/actions) in your plugin CI_

### CODE REVIEW

**Comment by vthiery** [comment]
Please hold on this one as I'd like to transfer the plugin to `asdf-community`. See https://github.com/asdf-community/infrastructure/pull/149

**Comment by vthiery** [comment]
The repository has been transferred: https://github.com/asdf-community/asdf-stratus-red-team

**Comment by vthiery** [comment]
@jthegedus please let me know if something is blocking this pr

**Review by jthegedus — APPROVED** [review]
Thanks, sorry for the delay.

**Pull request merged**
