### PR TITLE
Add stack plugin

### PR DESCRIPTION
**Pull request by sestrella**
Add [stack](https://docs.haskellstack.org/en/stable/README/) plugin

# Checklist

- [x] Provide a short description and link to your plugin.
- [x] Make sure you CI tests for your plugin and they are green.
- [x] `asdf-plugins` CI sanity checks are green on your PullRequest.

### CODE REVIEW

**Comment by smorimoto** [comment]
You should be able to write plugins without Python. You should not increase the dependencies, so replace the Python code.

**Comment by sestrella** [comment]
@smorimoto thank you for the feedback. I thought about going with Python since is usually already present in most OS, but I also see the point of "not increase the dependencies" so I'll try to migrate the code to BASH

**Comment by sestrella** [comment]
@smorimoto I just managed to migrate all code to BASH, I just wonder if you could take a second look, please?

**Review by smorimoto — APPROVED** [review]

**Comment by smorimoto** [comment]
Looks good!

**Comment by smorimoto** [comment]
Thanks @sestrella :)

**Comment by sestrella** [comment]
@smorimoto thank you for taking a second look!

**Comment by smorimoto** [comment]
Anytime!

**Pull request merged**
