### PR TITLE
feat: Hasura CLI

### PR DESCRIPTION
**Pull request by gurukulkarni**
# Checklist

- [x] Provide a short description and link to your plugin.
[Hasura GraphQL Engine](https://github.com/hasura/graphql-engine/tree/master/cli) is a blazing-fast GraphQL server that gives you instant, realtime GraphQL APIs over Postgres, with webhook triggers on database events, and remote schemas for business logic.
They Have a [CLI tool](https://github.com/hasura/graphql-engine/tree/master/cli) that is used for operations against the engine.

- [x] Make sure you CI tests for your plugin and they are green.

      If you are using github, you might want to use the
      `plugin_test` action from [asdf-actions](https://github.com/asdf-vm/actions)

- [x] `asdf-plugins` CI sanity checks are green on your PullRequest.

      You can test locally using:

      ```bash
      ./test_plugin.sh --file plugins/PLUGIN_FILE
      ```

## Other Information

If there is anything else that is relevant to your pull request include that
information here.

Thank you for contributing to asdf-plugins!

### CODE REVIEW

**Comment by ghostsquad** [comment]
@gurukulkarni can you rebase resolve the conflict with the readme? I think this would allow this be merged.

**Comment by gurukulkarni** [comment]
Yes sure will do that 👍🏼

**Comment by gurukulkarni** [comment]
> @gurukulkarni can you rebase resolve the conflict with the readme? I think this would allow this be merged.

@ghostsquad : It's Done :+1:

**Review by jthegedus — APPROVED** [review]

**Comment by jthegedus** [comment]
Thanks everyone!

**Pull request merged**
