### PR TITLE
Adds vim plugin

### PR DESCRIPTION
**Pull request by tsuyoshicho**
# Checklist

- [x] Provide a short description and link to your plugin.

      Add support Vim official repo.'s build and manage plugin.

- [x] Make sure you CI tests for your plugin and they are green.

     GitHub Actions Status:Commit

- [x] `asdf-plugins` CI sanity checks are green on your PullRequest.

      You can test locally using:

      ```bash
      ./test_plugin.sh --file plugins/PLUGIN_FILE
      ```

      local run
      ```
      $ ./test_plugin.sh --file plugins/vim
      Checking plugins/vim
      OK plugins/vim
      ```

## Other Information

This plugin is simply. If other plugin creator's plugin are more good, replace it.

### CODE REVIEW

**Comment by smorimoto** [comment]
It looks good overall. But, it would be better if users could pass the configure option. Would you like to give that a try?

**Comment by tsuyoshicho** [comment]
> It looks good overall. But, it would be better if users could pass the configure option. Would you like to give that a try?

Okay, but I do not know best practice in asdf plugin. Please suggest other plugin that  implement same or like option for example.

**Comment by smorimoto** [comment]
There's not much best practice there. For example, the PHP plugin has such an implementation.
https://github.com/asdf-community/asdf-php/blob/21cb6ceddc77522bd4ecb08ca7d8f99fb4b6c420/bin/install#L95-L99

**Comment by tsuyoshicho** [comment]
Thanks!! I work to it.
Wait for a little.

**Comment by smorimoto** [comment]
That looks good now. Is there any additional work you want to do?

**Comment by tsuyoshicho** [comment]
Currently nothing OK

**Comment by smorimoto** [comment]
Thanks @tsuyoshicho 🙂

**Pull request merged**
