### PR TITLE
fix: Fix incongruities

### LINKED ISSUE #827: Swift plugin was removed from the README.md
### Describe the Bug

https://github.com/asdf-vm/asdf-plugins/pull/39 removed swift plugin from the README.md, which must be an accident.

### Steps to Reproduce

see the README.md

### Expected Behaviour

swift plugin IS in the README.md

### Actual Behaviour

swift plugin is NOT in the README.md

### Environment

```shell
none
```

### PR DESCRIPTION
**Pull request by hyperupcall**
## Summary

There were several issues with listings such as:
- a plugin entry listed in `README.md`, but not in `./plugins`
- a plugin entry listed in `./plugins`, but not in `README.md`
- remote URLs of plugin entries out of sync (difference in repository, username)
- plugins not prefixed with `asdf-` when it should be
- whitespace formatting in `README.md` table

Closes #827

I used the following script to make sure everything was in sync: 

<details>

<summary> <code>check.sh</code> </summary>

```sh
#!/usr/bin/env bash

assert() {
  local file="$1"

  value=$(wc -l "$file" | cut -d' ' -f1)
  if [[ $value -ne 1 ]]; then
    echo "Not 1 line: $file"
    exit 1
  fi
}

# dir
> .hidden/.plugins-dir
for f in ./plugins/*; do
  # assert "$f"

  filename=${f##*/}
  url=$(cut -d= -f 2 "$f" | xargs)
  echo "$url" | grep -v .git
  url=${url%.git}
  name=${url#https://}
  name=${name#*/}

  echo "$name: $url" >> ".hidden/.plugins-dir"
done
a=$(sort .hidden/.plugins-dir)
echo "$a" > .hidden/.plugins-dir

# readme
> .hidden/.plugins-readme
sed -En 's/^\|.*?\| \[.*?\]\((.*?)\).*\[.*/\1/p' 'README.md' | while read -r url; do
  name=${url%.git}
  name=${name#https://}
  name=${name#*/}
  echo "$url" | grep .git
  
  echo "$name: $url" >> .hidden/.plugins-readme
done
b=$(sort .hidden/.plugins-readme)
echo "$b" > .hidden/.plugins-readme
```

</details>

I only noticed `./scripts/test_plugin.bash` afterwards, but it didn't seem to catch these errors.

In the future, I think it would be good to autogenerate the `README.md` entries, and files in `./plugins` from some `plugins.json` file. That way, these sorts of mistakes are eliminated.

## Checklist

- [x] Format with `scripts/format.bash`
- [x] Test locally with `scripts/test_plugin.bash --file plugins/<your_new_plugin_name>`
- [ ] Your plugin CI tests are green
  - _Tip: use the `plugin_test` action from [asdf-actions](https://github.com/asdf-vm/actions) in your plugin CI_

### CODE REVIEW

**Comment by hyperupcall** [comment]
And just to be note, changing the URL shouldn't have an effect because this repository is only used for _adding_ plugins, right? If a plugin is already added, then changing this won't do anything and redownloading the plugin will use the new remote url?

If this is not the case I can simply omit the `repository = *` changes

**Comment by jthegedus** [comment]
As I understand you're correct, so this change should be fine.

Thanks for doing this. I had intentions of adding something like https://github.com/dkhamsing/awesome_bot to validate URLs. Aside from going through the list of broken URLs being a painful task, we don't really have a protocol for how to manage community plugins when they're abandoned etc. And then there's the fact that I want to deprecate this URL with some form of in-built CLI search as maintaining this repo is just toil. And while making these fixes is good, automating the validation would add more toil.

**Review by jthegedus — APPROVED** [review]
Thanks!

**Comment by hyperupcall** [comment]
> And then there's the fact that I want to deprecate this URL with some form of in-built CLI search as maintaining this repo is just toil. And while making these fixes is good, automating the validation would add more toil.

Any idea of what that might look like? Would an alternative be searching GitHub for repositories tagged `asdf-plugin` and suggestions repositories based on that?

Because I think one advantage of this repository is that it acts like an index so `asdf` doesn't have to search and make API requests every time. So maybe it is better to keep this repository, but also reduce maintenance burden?

If you are OK with it, I was going to add a `plugins.json/toml` to reduce some of that burden. So there is a single source of truth for the plugins. With that maybe you can generate a specific file for the built-in CLI search idea as well? Of course I will also have to add some stuff for GitHub Actions. My main motivation is that I would like to easily autogenerate definitions for [repo](https://gerrit.googlesource.com/git-repo). That way, it's easier to download, modify, and sync all these repositories that we have.

I already have a 670-line manifest that looks something like:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<manifest>
    <project name="hensou/asdf-dotnet" revision="main" path="repos/asdf-dotnet" />
    <project name="emersonsoares/asdf-dotnet-core" revision="master" path="repos/asdf-dotnet-core" />
    <project name="NeoHsu/asdf-1password-cli" revision="master" path="repos/asdf-1password-cli" />
    <project name="grimoh/asdf-act" revision="master" path="repos/asdf-act" />
    ...
```

But as you might imagine, maintaining it separately is kind of annoying and other people might find something like this useful.

> we don't really have a protocol for how to manage community plugins when they're abandoned etc.

If the repository is popular enough, what are your general thoughts of forking it into `asdf-community/`?

**Comment by jthegedus** [comment]
Adding an index is definitely something we would do, but I don't think hosting it in the repo will be the way we go. As you have discovered we've got some other changes we are focusing on behind the scenes before we start working on removing or adding new features like search.

As for your `.toml` file file, I don't particularly want to commit to a new file with specification before we discuss the development of a first-party feature that takes advantage of that feature. A lot of the issues we have with asdf is because one person requested something to make their own workflow better without looking at the con sequences of those decisions in the future. This repo is the perfect example of that. Maintenance is high, it supports only one repo per plugin name. Other examples from the core is that plugin names are weird as you can name them whatever you want at installation time, but then sharing them is broken because the name needs to be the same across all the user machines. Plugins are global to the machine and not local to the project so you can't use different plugins with conflicting names across projects... I could go on.

So for any index, file format, structure etc I would like to deliver it with the actual feature in the core that would utilise it where we can work out the aforementioned kinks.

**Comment by hyperupcall** [comment]
> As for your .toml file file, I don't particularly want to commit to a new file with specification before we discuss the development of a first-party feature that takes advantage of that feature.

Sure, that makes sense. Although I would argue that if we autogenerate the generation of files in the `./plugins`, core is would already be taking advantage of this feature, I would understand if that is not specific enough.

> So for any index, file format, structure etc I would like to deliver it with the actual feature in the core that would utilise it where we can work out the aforementioned kinks.

:+1:

**Pull request merged**
