### PR TITLE
Add a Coq plugin repo

### PR DESCRIPTION
**Pull request by gingerhot**
Add a Coq plugin git repo address: https://github.com/gingerhot/asdf-coq

### CODE REVIEW

**Comment by gingerhot** [comment]
Is there someone help to check the failed checks:

```
2.06s
$ bash test.sh
Plugin build failed: https://travis-ci.org/marciogm/asdf-crystal
Plugin build failed: https://travis-ci.org/asdf-vm/asdf-elixir
Plugin build failed: https://travis-ci.org/rkyleg/asdf-julia
Plugin build failed: https://travis-ci.org/smashedtoatoms/asdf-openresty
Plugin build failed: https://travis-ci.org/odarriba/asdf-php
Plugin build failed: https://travis-ci.org/Stratus3D/asdf-rebar
Total plugins with failed builds: 6
The command "bash test.sh" exited with 6.
Done. Your build exited with 1.
```

Thanks~

**Comment by vic** [comment]
Hey, sorry for the loong delay. Havent been near my laptop for some months. Looks like your plugin build is ok, but others are failing, so I'll just rebase and merge. Thank you.

**Comment by Stratus3D** [comment]
@gingerhot this plugin should also be added to the plugin list in the readme.

**Comment by gingerhot** [comment]
@vic no matter~ Thank you.

@Stratus3D I've created another request #29.

**Pull request merged**
