### PR TITLE
WIP: fix: remove bazel plugin

### PR DESCRIPTION
**Pull request by jaimem88**
The bazel plugin listed in the README does not work.

The repository https://github.com/rajatvig/asdf-bazel
hasn't been updated since Dec 2018 and issues are not enabled.

Closes https://github.com/asdf-vm/asdf-plugins/issues/350.

# Checklist

- [ ] Provide a short description and link to your plugin.

- [ ] Make sure you CI tests for your plugin and they are green.

      If you are using github, you might want to use the
      `plugin_test` action from [asdf-actions](https://github.com/asdf-vm/actions)

- [ ] `asdf-plugins` CI sanity checks are green on your PullRequest.

      You can test locally using:

      ```bash
      ./test_plugin.sh --file plugins/PLUGIN_FILE
      ```

## Other Information

If there is anything else that is relevant to your pull request include that
information here.

Thank you for contributing to asdf-plugins!

### CODE REVIEW

**Comment by smorimoto** [comment]
I don't know if it's a good idea to just remove it, but certainly it's a problem that it doesn't work.

**Comment by jaimem88** [comment]
@smorimoto fair enough. It seems like the repo was updated in https://github.com/asdf-vm/asdf-plugins/pull/57. I have actually tested with the original repo https://github.com/mrinalwadhwa/asdf-bazel so I will update

**Comment by jaimem88** [comment]
Actually the original repo has outdated hardcoded versions https://github.com/mrinalwadhwa/asdf-bazel/issues/4

I have pinged the owner of the current repo https://github.com/asdf-vm/asdf-plugins/issues/350#issuecomment-759940989, I will WIP this PR in the meantime

**Comment by jaimem88** [comment]
There is no `latest` version available in bazel, so a numbered version needs to be used. Closing now.

**Pull request closed without merging**
