### PR TITLE
Add Fairwinds Ops Nova plugin.

### PR DESCRIPTION
**Pull request by elementalvoid**
# Checklist

- [x] Provide a short description and link to your plugin.
      A [plugin](https://github.com/elementalvoid/asdf-nova) for [FairwindsOps Nova](https://github.com/FairwindsOps/Nova). Nova describes itself as:
>Nova scans your cluster for installed Helm charts, then cross-checks them against all known Helm repositories. If it finds an updated version of the chart you're using, or notices your current version is deprecated, it will let you know.

- [x] Make sure you CI tests for your plugin and they are green.
      [GitHub Actions Status](https://github.com/elementalvoid/asdf-nova/actions)

- [x] `asdf-plugins` CI sanity checks are green on your PullRequest.

      ❯ ./test_plugin.sh --file plugins/nova
      Checking plugins/nova
      OK plugins/nova

### CODE REVIEW

**Review by smorimoto — APPROVED** [review]

**Comment by smorimoto** [comment]
@elementalvoid Could you resolve the conflicts?

**Comment by elementalvoid** [comment]
@smorimoto Conflicts resolved!

**Comment by smorimoto** [comment]
All green!

**Comment by smorimoto** [comment]
Thanks @elementalvoid!

**Comment by smorimoto** [comment]
And I'm sorry for the late review. I was so busy last month that I didn't have time to review this.

**Pull request merged**
