### PR TITLE
Added play framework plugin

### PR DESCRIPTION
**Pull request by teixeiradiego**

### CODE REVIEW

**Comment by Stratus3D** [comment]
It looks like your Travis CI build is failing.

**Comment by teixeiradiego** [comment]
> It looks like your Travis CI build is failing.

The plugin-test script from master of the asdf repository isn't working. It always gives the message "FAILED: Incorrect permissions on /tmp/asdf.gnwZ/plugins/play/bin/*. Must be executable by asdf". But I manually tested it and I'm using the plugin with no problem. 

It depends on some changes I've made on the reshim script and this changes are already merged into the master branch of the asdf repository. This is why I didn't change Travis CI to use the asdf stable. I hope the test script will be fixed soon and my test starts working.

**Comment by Stratus3D** [comment]
@teixeiradiego can you try again? We've released a couple new versions of asdf, and the `plugin-test` command is working for many other plugins.

**Comment by Stratus3D** [comment]
Closing since it's been a while since there has been any activity on this PR.

**Pull request closed without merging**
