### PR TITLE
feat: add dynatrace-monaco plugin

### PR DESCRIPTION
**Pull request by nsaputro**
## Summary

Description:

- Tool repo URL: https://github.com/Dynatrace/dynatrace-configuration-as-code
- Plugin repo URL: https://github.com/nsaputro/asdf-monaco

## Checklist

- [x] Format with `scripts/format.bash`
- [x] Test locally with `scripts/test_plugin.bash --file plugins/<your_new_plugin_name>`
- [x] Your plugin CI tests are green
  - _Tip: use the `plugin_test` action from [asdf-actions](https://github.com/asdf-vm/actions) in your plugin CI_

### CODE REVIEW

**Review by jthegedus — COMMENTED** [review]
I feel like this should be called `dynatrace-monaco` or something?

**Review by jthegedus — CHANGES_REQUESTED** [review]
please rebase

**Comment by nsaputro** [comment]
@jthegedus I have changed the name and rebased the the change. Please check

**Review by jthegedus — APPROVED** [review]
Thanks mate!

**Pull request merged**
