### PR TITLE
Add "getenvoy" plugin

### PR DESCRIPTION
**Pull request by superbrothers**
This PR adds a new plugin "getenvoy".

### CODE REVIEW

**Comment by imbsky** [comment]
It looks good, but see this PR and make similar changes to the plugin.
https://github.com/pfnet-research/asdf-clusterctl/pull/1

**Comment by superbrothers** [comment]
Sorry, I just noticed that PR. I'll fix it on superbrothers/get-envoy soon.

**Comment by imbsky** [comment]
No worries :) Thanks for your quick response.

**Comment by superbrothers** [comment]
I've fixed it at https://github.com/superbrothers/asdf-getenvoy/pull/1.

**Comment by imbsky** [comment]
Thanks @superbrothers :)

**Pull request merged**
